<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

require_once ('blocks/blocks_autoload.php');

use Blocks\WidgetGridBlock;
use Blocks\Widget;

remove_action( 'genesis_loop', 'genesis_do_loop' );

//remove_action( 'genesis_entry_content', 'genesis_do_post_content' );

add_action( 'genesis_before_loop', 'genesis_do_search_title' );
/**
 * Echo the title with the search term.
 *
 * @since 1.9.0
 */
function genesis_do_search_title() {
	
	$originalSearch = get_search_query();
	
	$search = filterSearchTerm(get_search_query());
	
	if (trim($originalSearch) != trim($search))
	{
		$search = "That search term is not allowed.";
	}
	
	$title = sprintf( '<div class="archive-description"><h2 class="archive-title">%s <span class="has-theme-primary-color">%s</span></h2></div>', apply_filters( 'genesis_search_title_text', __( 'Search Results for:', 'genesis' ) ), $search );

	echo apply_filters( 'genesis_search_title_output', $title ) . "\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped

}

/**
 * Outputs the search results using the widget grid.
 */
function seaport_museum_do_search_loop () {
	
	if ( class_exists( 'SWP_Query' ) ) {
		//Use SearchWP SWP_Query
		$query = getPostsFromSearchWpQuery();
	}
	else {
		//Fallback to WordPress Native Search
		$query = getPostsFromWpQuery();
	}
	
	
	
	if ( $query->have_posts() ) {
		
		foreach ($query->posts as $post)
		{
			$widget = Widget::getWidgetHtml( $post, 'has-theme-primary-background-color' );
			
			echo $widget;
		}
		
	}
	else
	{
		echo '<p>No Search Results Found.</p>';
	}

}

/**
 * @return WP_Query
 */
function getPostsFromWpQuery() {
	
	$s = get_search_query();
	
	// WP_Query arguments
	$args = array(
		's'      => get_search_query(),
		'posts_per_page' => 100,
		'orderby' => 'title'
	);
	
	$query = new WP_Query( $args );
	
	return $query;
}

/**
 * Use SearchWP's SWP_Query to perform a search using the default engine
 */
function getPostsFromSearchWpQuery() {
	
	$search = filterSearchTerm(get_search_query());
	
	// SWP_Query arguments
	$swp_query = new SWP_Query(
		array(
			's' => $search, // search query
			'posts_per_page' => 100,
			'nopaging' => false,
		)
	);
	
	
	return $swp_query;
}

add_action('post_class', 'seaport_museum_cp_post_class');

function seaport_museum_cp_post_class() {
	return ['archive-widget'];
}

//block-post-grid
add_action( 'genesis_before_loop', 'seaport_museum_search_open', 11);

add_action( 'genesis_loop', 'seaport_museum_do_search_loop', 12 );

//close the div wrapper
add_action('genesis_after_loop', 'seaport_museum_search_close', 20);

genesis();

/**
 *  Opens a Div tag around archive post widgets
 *
 * Be sure to call seaport_museum_archive_close()
 */
function seaport_museum_search_open()
{
	echo "<div class='block-post-grid'>";
}

/**
 * Closes the Div tag around archive post widgets.
 *
 * Call after seaport_museum_archive_open()
 */
function seaport_museum_search_close()
{
	echo "</div>";
}


function filterSearchTerm($search)
{
	return str_replace(['https://', 'http://', '.com', '.co.uk', '.ru', '.', '/'], '', $search);
}
